// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// unwrap_array_impl
NumericMatrix unwrap_array_impl(const NumericMatrix& array, double dAlpha, double rMax, double dR, double missing);
RcppExport SEXP _search_unwrap_array_impl(SEXP arraySEXP, SEXP dAlphaSEXP, SEXP rMaxSEXP, SEXP dRSEXP, SEXP missingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type array(arraySEXP);
    Rcpp::traits::input_parameter< double >::type dAlpha(dAlphaSEXP);
    Rcpp::traits::input_parameter< double >::type rMax(rMaxSEXP);
    Rcpp::traits::input_parameter< double >::type dR(dRSEXP);
    Rcpp::traits::input_parameter< double >::type missing(missingSEXP);
    rcpp_result_gen = Rcpp::wrap(unwrap_array_impl(array, dAlpha, rMax, dR, missing));
    return rcpp_result_gen;
END_RCPP
}
// cdf_area
double cdf_area(const NumericVector& a, const NumericVector& b);
RcppExport SEXP _search_cdf_area(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(cdf_area(a, b));
    return rcpp_result_gen;
END_RCPP
}
// cdf_max
double cdf_max(const NumericVector& a, const NumericVector& b);
RcppExport SEXP _search_cdf_max(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(cdf_max(a, b));
    return rcpp_result_gen;
END_RCPP
}
// edit_dist
size_t edit_dist(const CharacterVector& a, const CharacterVector& b);
RcppExport SEXP _search_edit_dist(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(edit_dist(a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_search_unwrap_array_impl", (DL_FUNC) &_search_unwrap_array_impl, 5},
    {"_search_cdf_area", (DL_FUNC) &_search_cdf_area, 2},
    {"_search_cdf_max", (DL_FUNC) &_search_cdf_max, 2},
    {"_search_edit_dist", (DL_FUNC) &_search_edit_dist, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_search(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
