# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unwrap_array_impl <- function(array, dAlpha, rMax, dR, missing) {
    .Call(`_search_unwrap_array_impl`, array, dAlpha, rMax, dR, missing)
}

cdf_area <- function(a, b) {
    .Call(`_search_cdf_area`, a, b)
}

cdf_max <- function(a, b) {
    .Call(`_search_cdf_max`, a, b)
}

edit_dist_impl <- function(x, y) {
    .Call(`_search_edit_dist_impl`, x, y)
}

